### ISSUE TITLE
Forge character sheet not found

### ISSUE THREAD

**Issue by Astrotech89** [sparkcity/fvtt-me5e#10]
Hey Spark,

Not sure if it's an issue on your end or not but I started using Fvtt on the forge.  Things are looking good but for some reason I can't find your character sheet (i.e paragon, renegade, regular).  I'm trying to see if anyone on the Forge discord can help but thought you should know too.  Looks like you had issues in the Forge with v.1.4 so I thought I'd double check with you on that

**Comment by Astrotech89** [comment]
Also the shield hit points seem to be gone.  The following screen grab is from the forge
![Screenshot 2020-09-25 231531](https://user-images.githubusercontent.com/20007225/94331887-0ce09700-ff85-11ea-9046-846fad5a92ac.png)

**Comment by sparkcity** [comment]
Hey, thanks for letting me know the update didn't quite fix things. There's a fairly significant bug in the sheet that I'm working on right now, but the reason it's not showing up is just a path issue. The way I was telling it to find things doesn't work on Forge, so I need to fix that as we'll It's 2 am right now, but I'll be working on it tomorrow.

**Comment by Astrotech89** [comment]
Hey Spark,

So I was able to reach KaKaRoTo and he was able to fix the issue on his end
![image](https://user-images.githubusercontent.com/20007225/94332014-2afac700-ff86-11ea-9f5c-f0c6bcac34e7.png)
