### ISSUE TITLE
Vehicle Handling Custom Skill bug

### ISSUE THREAD

**Issue by baerauble** [sparkcity/fvtt-me5e#12]
![foundrybug](https://user-images.githubusercontent.com/72077765/94550929-2bab8b80-021a-11eb-8069-3670f37a9e3c.png)
Adding proficiency in the Vehicle Handling skill causes both the skill itself and the initiative field to bug out, causing a NaN error. Also causes all changes to character sheet after that point to only show after sheet is closed and re-opened. Bug shows up after world/foundry is closed with the skill proficiency active.
Leaving the skill non-proficient keeps character sheet valid and functional, but removing proficiency once error has occurred does not correct issue. Issue is specific to the character that has the proficiency.

**Comment by sparkcity** [comment]
Have you updated to 1.7? If you made this sheet prior to updating to 1.7, please delete the sheet and remake it. Vehicle Handling should no longer have that toggle button available.
