### ISSUE TITLE
Compendium: Class Features

### ISSUE THREAD

**Issue by sparkcity** [sparkcity/fvtt-me5e#2]
A compendium of class features (also maybe subclasses?)

**Comment by Astrotech89** [comment]
Yeah class and subclass features.  Like for example Infiltrators can cloak.  Also some races have race features like Geth can engage Hunter Mode kinda like a berserker mode.

**Comment by sparkcity** [comment]
Compendiums completed: Classes with subclasses, class and subclass features, racial features.
