### ISSUE TITLE
Can't edit speed

### ISSUE THREAD

**Issue by Astrotech89** [sparkcity/fvtt-me5e#23]
Hi there,

Looks like during the last update, everyone's speed reverted back to 30ft and I can't seem to edit the speed.

![image](https://user-images.githubusercontent.com/20007225/99160262-286d4180-269a-11eb-886a-618b18b6fdd6.png)

**Comment by sparkcity** [comment]
This is actually not a module issue, this is just a new thing in DND5E as a system.

You have to edit speed through Configure Movement Speed on the Attributes tab.

**Comment by Astrotech89** [comment]
Ah, then it looks like it is now a metric issue now.
