### ISSUE TITLE
Character sheet could use a shield tracker

### ISSUE THREAD

**Issue by Astrotech89** [sparkcity/fvtt-me5e#5]
Hey Spark,

I'm loving the updates.  This looks amazing so far.  I just noticed though that there is no slot on the character sheet for shields (i.e the shield points on top of the hit points). 

Cheers,
Astro

**Comment by sparkcity** [comment]
v1.3 - Place for tracking shields / max shields and shield regeneration added to header.

Thank you for the reminder!
